version: '3'

services:
  backend:
    build : ./backend
    container_name: my-backend
    ports:
     - "5000:5000"
    env_file:
      - ./backend/src/.env

  frontend:
    build: ./frontend
    container_name: my-frontend
    ports:
     - "4200:4200"
    environment:
      - API_URL=http://backend:5000
    depends_on:
      - backend
